# Generated by Django 5.2.5 on 2025-08-15 08:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ThongBao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tieu_de', models.CharField(max_length=255, verbose_name='Tiêu đề')),
                ('noi_dung', models.TextField(verbose_name='Nội dung')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
                ('nguoi_dang', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Người đăng')),
            ],
            options={
                'verbose_name': 'Thông báo',
                'verbose_name_plural': 'Các thông báo',
            },
        ),
    ]
