# Generated by Django 5.2.5 on 2025-08-16 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhanAnh',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_ten', models.CharField(max_length=150, verbose_name='Họ và tên người gửi')),
                ('so_dien_thoai', models.CharField(max_length=15, verbose_name='Số điện thoại liên hệ')),
                ('noi_dung', models.TextField(verbose_name='Vị trí sự cố hoặc nội dung góp ý')),
                ('hinh_anh', models.ImageField(blank=True, null=True, upload_to='uploads/phananh/', verbose_name='Hình ảnh sự cố')),
                ('tinh_trang', models.CharField(choices=[('moi', 'Mới tiếp nhận'), ('dang_xu_ly', 'Đang xử lý'), ('da_xu_ly', 'Đã xử lý')], default='moi', max_length=20, verbose_name='Tình trạng')),
                ('ngay_gui', models.DateTimeField(auto_now_add=True, verbose_name='Ngày gửi')),
            ],
            options={
                'verbose_name': 'Phản ánh',
                'verbose_name_plural': 'Quản lý Phản ánh',
            },
        ),
    ]
