# Generated by Django 5.2.5 on 2025-08-15 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HoDan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('so_nha', models.CharField(max_length=50, verbose_name='Số nhà')),
                ('khu_vuc', models.CharField(max_length=100, verbose_name='Khu vực (Hẻm, Tổ...)')),
                ('dia_chi_cu_the', models.CharField(blank=True, max_length=255, null=True, verbose_name='Địa chỉ cụ thể')),
                ('ten_chu_ho', models.CharField(max_length=150, verbose_name='Tên chủ hộ')),
                ('so_dien_thoai', models.CharField(blank=True, max_length=15, null=True, verbose_name='Số điện thoại')),
                ('tinh_trang_ho', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tình trạng hộ')),
            ],
            options={
                'verbose_name': 'Hộ dân',
                'verbose_name_plural': 'Quản lý Hộ dân',
            },
        ),
        migrations.CreateModel(
            name='NhanKhau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ho_va_ten', models.CharField(max_length=150, verbose_name='Họ và tên')),
                ('ngay_sinh', models.DateField(blank=True, null=True, verbose_name='Ngày sinh')),
                ('gioi_tinh', models.CharField(choices=[('Nam', 'Nam'), ('Nữ', 'Nữ'), ('Khác', 'Khác')], max_length=5, verbose_name='Giới tính')),
                ('so_cccd', models.CharField(blank=True, max_length=12, null=True, unique=True, verbose_name='Số CCCD/CMND')),
                ('cong_viec_hien_nay', models.CharField(blank=True, max_length=255, null=True, verbose_name='Công việc hiện nay')),
                ('noi_o_hien_nay', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nơi ở hiện nay')),
                ('ho_dan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dancu.hodan', verbose_name='Hộ dân')),
            ],
            options={
                'verbose_name': 'Nhân khẩu',
                'verbose_name_plural': 'Quản lý Nhân khẩu',
            },
        ),
    ]
