# Generated by Django 5.2.5 on 2025-08-15 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancu', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hodan',
            name='ten_chu_ho',
        ),
        migrations.AddField(
            model_name='hodan',
            name='chu_ho',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ho_dan_la_chu_ho', to='dancu.nhankhau', verbose_name='Chủ hộ'),
        ),
        migrations.AddField(
            model_name='nhankhau',
            name='tinh_trang',
            field=models.CharField(choices=[('thuong_tru', 'Thường trú'), ('tam_tru', 'Tạm trú'), ('vang_mat', 'Vắng mặt tại địa phương'), ('da_mat', 'Đã mất')], default='thuong_tru', max_length=20, verbose_name='Tình trạng'),
        ),
        migrations.AlterField(
            model_name='nhankhau',
            name='ho_dan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dancu.hodan', verbose_name='Thuộc hộ dân'),
        ),
    ]
