# Generated by Django 5.2.5 on 2025-08-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancu', '0002_remove_hodan_ten_chu_ho_hodan_chu_ho_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='nhankhau',
            name='quan_he_chu_ho',
            field=models.CharField(choices=[('chu_ho', 'Chủ hộ'), ('vo', 'Vợ'), ('chong', 'Chồng'), ('con', 'Con'), ('bo', 'Bố'), ('me', 'Mẹ'), ('ong', 'Ông'), ('ba', 'Bà'), ('chau', 'Cháu'), ('khac', 'Khác')], default='chu_ho', max_length=20, verbose_name='Quan hệ với chủ hộ'),
        ),
    ]
