# Generated by Django 5.2.5 on 2025-08-17 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dancu', '0003_nhankhau_quan_he_chu_ho'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hodan',
            name='tinh_trang_ho',
            field=models.CharField(choices=[('binh_thuong', 'Bình thường'), ('kinh_doanh', 'Hộ kinh doanh'), ('cho_thue', 'Hộ cho thuê'), ('ho_ngheo', 'Hộ nghèo'), ('can_ngheo', 'Hộ cận nghèo'), ('chinh_sach', 'Gia đình chính sách')], default='binh_thuong', max_length=20, verbose_name='Tình trạng hộ'),
        ),
    ]
