# Generated by Django 5.2.5 on 2025-08-16 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BieuMau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_bieu_mau', models.CharField(max_length=255, verbose_name='Tên biểu mẫu')),
                ('mo_ta', models.TextField(blank=True, null=True, verbose_name='Mô tả ngắn')),
                ('file_dinh_kem', models.FileField(upload_to='uploads/bieumau/', verbose_name='File đính kèm')),
                ('ngay_dang', models.DateTimeField(auto_now_add=True, verbose_name='Ngày đăng')),
            ],
            options={
                'verbose_name': 'Biểu mẫu',
                'verbose_name_plural': 'Quản lý Biểu mẫu',
                'ordering': ['-ngay_dang'],
            },
        ),
    ]
